[package]
name = "drawing_board_client"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = {version = "0.29.1", features = ["persistence"]}
egui = "0.29.1"
quinn = "0.11.5"
serde = "1.0.211"
