[package]
name = "drawing_board_server"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.91"
quinn = "0.11.5"
rcgen = "0.13.1"
serde = "1.0.211"
tokio = {version = "1.41.0", features = ["full"]}
