[package]
name = "common_definitions"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib"]
path = "src/lib.rs"

[dependencies]
serde = "1.0.211"
uuid = {version = "1.11.0", features = ["serde", "v4"]}
serde_json = "1.0.132"